FIX use Token attrs in search (#26)
This commit fixes an issue with .search() when by_tokens is set to False.
TypeError: 'Token' object is not subscriptable